### ISSUE TITLE
Django Modal Update - Placement

### ISSUE THREAD

**Issue by CDC-IITDH** [CDC-IITDH/cdc-placement-website-backend#2]
- Django Models needs Update to incorporate more fields
- Update Placement model in ``models.py``
- Required Fields:
    - Company name*
    - Website Link*
    - Brief about the company PDF - optional
    - Brief about company in words - optional
    - Company Address*
    - City*
    - State*
    - Country*
    - Pin*
    - Type of Organization*
    - Nature of business*
    - Job Description PDF - optional
    - Job designation*
    - Location of Job*
    - Job details*
    - Tentative date of joining*
    - Are MS research scholars (postgraduates) eligible to apply?*
    - Tentative number of offers - optional 
    - Salary Desc PDF - optional
    - CTC*
    - Gross*
    - Take home*
    - Bonus - optional 
    - Details of Bond
    - Selection process - Checkboxes*
    - Brief about the selection process PDF
    - Brief about the selection process words
    - Other student requirements - eg. CPI, branch etc
    - Contact person
    - Email
    - Mobile number
> '*' represents an necessary field

**Comment by Samyc2002** [comment]
I'd like to take up the issue.

**Comment by Samyc2002** [comment]
PR made.

**Comment by gowtham3105** [comment]
I already made a PR with the required changes.
